name: macOS tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [macos-latest]
          go-version: ['1.22.x']

    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
    
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
    
        - name: Install Dependencies
          run: brew install libpcap libusb p7zip

        - name: Run Tests
          run: |
            env GO111MODULE=on make test
        